--
-- Table structure for table `transactions`
--

CREATE TABLE IF NOT EXISTS `transactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` varchar(20) NOT NULL,
  `time` varchar(40) NOT NULL,
  `account_holder_type` varchar(10) DEFAULT NULL,
  `account_type` varchar(10) DEFAULT NULL,
  `sec_code` varchar(10) DEFAULT NULL,
  `amount` decimal(11,2) NOT NULL,
  `tax` decimal(11,2) DEFAULT '0.00',
  `payment` varchar(20) NOT NULL,
  `orderdescription` varchar(254) DEFAULT NULL,
  `ipaddress` varchar(25) DEFAULT NULL,
  `firstname` varchar(30) NOT NULL,
  `lastname` varchar(30) NOT NULL,
  `company` varchar(60) NOT NULL,
  `address1` varchar(60) NOT NULL,
  `city` varchar(60) NOT NULL,
  `state` varchar(60) NOT NULL,
  `zip` varchar(30) NOT NULL,
  `country` varchar(50) NOT NULL,
  `phone` varchar(50) NOT NULL,
  `fax` varchar(50) DEFAULT NULL,
  `email` varchar(150) NOT NULL,
  `orderid` varchar(25) NOT NULL,
  `transactionid` int(15) DEFAULT NULL,
  `authcode` varchar(35) DEFAULT NULL,
  `capture_transactionid` int(11) DEFAULT NULL,
  `capture` tinyint(1) DEFAULT NULL,
  `refund_transactionid` int(11) DEFAULT NULL,
  `tracking_number` varchar(50) DEFAULT NULL,
  `shipping_carrier` varchar(10) DEFAULT NULL,
  `validated` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `orderid` (`orderid`),
  KEY `transactionid` (`transactionid`),
  KEY `capture` (`capture`),
  KEY `authcode` (`authcode`),
  KEY `type` (`type`),
  KEY `tracking_id` (`tracking_number`),
  KEY `validated` (`validated`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
